(QENG-4823) Reduce reaper exceptionality
puppetlabs/aws_resource_reaper pull request #4
Opened 2017-04-26 23:00 UTC by tvpartytonight

Previous to this commit, the reaper used exceptions for flow control;
this change removes that exceptional behavior.

2017-05-01 22:45 UTC, kevpl requested changes

2017-05-01 22:45 UTC, kevpl commented on lambdas/ec2/reaper.py
> +    return
@tvpartytonight I'm confused as to why this is here. If you're not returning something, shouldn't we just let the function end rather than having an empty return? Am I missing something here?

2017-05-01 22:45 UTC, kevpl commented on lambdas/ec2/reaper.py
> +def terminate_instance(ec2_instance, message='Terminating EC2 instance'):
@tvpartytonight it seems that providing a default `message` here will allow people to call this function without providing more context, which could be needed in further debugging / maintenance. It looks like all of your references to this function do provide messages, so why don't we not provide a default & fail if people don't provide one, making this function much more informative & easier to work with in the future?

2017-05-03 17:41 UTC, tvpartytonight commented on lambdas/ec2/reaper.py
> +    return
Not missing anything, just being overly verbose. 👍

2017-05-03 17:55 UTC, tvpartytonight commented
@kevpl comments addressed. Ready for another look.

2017-05-04 20:29 UTC, kevpl approved these changes

2017-05-04 20:38 UTC, merged